import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import SignOut from "@/components/SignOut";
import ContextProvider from "./contextProvider";
import SignIn from "@/components/SignIn";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable}`}>
        <ContextProvider>
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
